#!/bin/bash

set -e
grench eval "(do (require '[laundromat.core :reload true]) (require '[laundromat.core-test :reload true]))"
grench eval "(do (require 'clojure.test) (clojure.test/run-all-tests #\"laundromat.*\"))"
